int rledecode(int argc, char **argv);
int validate_args(int argc, char **argv);
int check_number_of_args(int argc);
int parse_arg(int arg_index, char *arg);
int rleplay_file_exists(char *filename);
int is_valid_prefix(char *prefix);
int handle_arg1(char *filename);
int handle_arg2(char *arg2);
int handle_arg3(char *arg3);
int handle_arg4(char *arg4);
void decode_file(int to_ppm, char **argv);
void decode_to_stdout(char **argv);
void decode_to_ppm(char **argv);